# The URL the site will be built for
base_url = "https://gabrielkoerich.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# The site title and description
title = "Gabriel Koerich"
description = "Senior Software Engineer | Rust • Solana • PHP • Laravel"

# The default language; used in feeds
default_language = "en"

# When set to "true", the generated HTML files are minified
minify_html = true

# Whether to generate a RSS feed
generate_feeds = true
feed_filenames = ["rss.xml"]

# The taxonomies to be rendered for the site and their configuration of the default languages
taxonomies = [{ name = "tags", feed = true }]

[extra]
# Put all your custom variables here
author = "Gabriel Koerich"
linkedin = "https://linkedin.com/in/gabrielkoerich"
github = "https://github.com/gabrielkoerich"
email = "gabrielmk@gmail.com"
